
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llauros/microservice-repo
          search-paths: fornecedor
          
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /home/lucas/Projects/FloricultureSystem/microservice-repo